binary = (bin(int('z',36))[2:])
octal= (oct(int('z',36))[2:])
hexadecimal = (hex(int('z',36))[2:])
print("The value of binary of give no is",binary)
print("The value of octal of give no is",octal)
print("The value of hexadecimal of give no is",hexadecimal)